name: Extension Builder

on: 
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - run: yarn
      - run: export COMMIT=$(git rev-parse --short "$GITHUB_SHA") && yarn build
      - name: Easy Zip Files
        uses: vimtor/action-zip@v1
        with:
          files: build/
          dest: build.zip
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
            name: build
            path: |
              ./build.zip
